[package]
name = "udp_send_test"
version = "0.1.0"
authors = ["Torkel <torkel@voysys.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
